SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Mitglied;
DROP TABLE IF EXISTS Bestellung;
DROP TABLE IF EXISTS Lieferant;
DROP TABLE IF EXISTS Kocht;
DROP TABLE IF EXISTS OrderItem;
DROP TABLE IF EXISTS PrimeKunde;
DROP TABLE IF EXISTS Benutzer;
DROP TABLE IF EXISTS Warenkorb;
DROP TABLE IF EXISTS Gericht;
DROP TABLE IF EXISTS Restaurant;
DROP TABLE IF EXISTS App;

SET FOREIGN_KEY_CHECKS = 1;